-- Run after schema.sql. Seeds existing content; does not overwrite admin edits.
insert into public.content(kind,slug,title,summary,image,image_alt,tags,data,published,sort_order) values ('event','genesis','AI Hackathon: Genesis 2026','48 hours to build the next generation of autonomous intelligence.','/about-assets/ai_hackathon.jpg','AI Hackathon: Genesis 2026',array['AI','Software','Hackathon'],'{"id":"genesis","title":"AI Hackathon: Genesis 2026","shortTitle":"AI HACKATHON","subtitle":"GENESIS 2026","startDate":"2026-12-05","endDate":"2026-12-07","date":"Dec 05–07, 2026","location":"Tech Innovation Hub","image":"hackathon","description":"48 hours to build the next generation of autonomous intelligence.","tags":["AI","Software","Hackathon"],"accentColor":"#00e5ff","prizePool":"3,00,000","symbol":"01","homeBeyond":true,"homeExperience":true,"registrationOpen":false}'::jsonb,true,0) on conflict(slug) do nothing;
insert into public.content_details(content_id,body) select id,'The club will share the full schedule and participation requirements here.' from public.content where slug='genesis' on conflict(content_id) do nothing;
insert into public.content(kind,slug,title,summary,image,image_alt,tags,data,published,sort_order) values ('event','robowars','RoboWars: Steel & Sparks','The ultimate combat robotics competition. Build, fight, survive. 30+ teams competing for glory.','/showcase-assets/rover.jpg','RoboWars: Steel & Sparks',array['Hardware','Combat','Robotics'],'{"id":"robowars","title":"RoboWars: Steel & Sparks","shortTitle":"ROBOWARS","subtitle":"STEEL & SPARKS","startDate":"2026-11-15","endDate":"2026-11-15","date":"Nov 15, 2026","location":"Main Arena","image":"robotics","description":"The ultimate combat robotics competition. Build, fight, survive. 30+ teams competing for glory.","tags":["Hardware","Combat","Robotics"],"accentColor":"#ffc107","prizePool":"6,00,000","symbol":"02","homeBeyond":true,"homeExperience":true,"registrationOpen":false}'::jsonb,true,1) on conflict(slug) do nothing;
insert into public.content_details(content_id,body) select id,'The club will share the full schedule and participation requirements here.' from public.content where slug='robowars' on conflict(content_id) do nothing;
insert into public.content(kind,slug,title,summary,image,image_alt,tags,data,published,sort_order) values ('event','iot-summit','IoT Smart Home Summit','Showcasing student-built home automation systems and advanced smart sensors.','/showcase-assets/vision.jpg','IoT Smart Home Summit',array['IoT','Sensors','Showcase'],'{"id":"iot-summit","title":"IoT Smart Home Summit","shortTitle":"IoT SUMMIT","subtitle":"SMART HOME EDITION","startDate":"2026-08-22","endDate":"2026-08-22","date":"Aug 22, 2026","location":"Auditorium B","image":"iot","description":"Showcasing student-built home automation systems and advanced smart sensors.","tags":["IoT","Sensors","Showcase"],"accentColor":"#ff4ca0","prizePool":"1,50,000","symbol":"03","homeBeyond":true,"homeExperience":true,"registrationOpen":false}'::jsonb,true,2) on conflict(slug) do nothing;
insert into public.content_details(content_id,body) select id,'The club will share the full schedule and participation requirements here.' from public.content where slug='iot-summit' on conflict(content_id) do nothing;
insert into public.content(kind,slug,title,summary,image,image_alt,tags,data,published,sort_order) values ('project','rover','ATLAS / ROVER','What if a small rover could explore an unfamiliar space and find its own way back?','/showcase-assets/rover.jpg','ATLAS / ROVER',array['Navigation','Sensors','Embedded control'],'{"category":"robotics","subtitle":"EXP—01 / ROBOTICS CONCEPT","status":"Concept","homeProject":true}'::jsonb,true,0) on conflict(slug) do nothing;
insert into public.content_details(content_id,body) select id,'The first experiment

Start with a wheeled platform and a distance sensor. Read the surroundings, stop before an obstacle, then add a simple navigation loop. This is a concept study, not a completed SAC project.' from public.content where slug='rover' on conflict(content_id) do nothing;
insert into public.content(kind,slug,title,summary,image,image_alt,tags,data,published,sort_order) values ('project','vision','IRIS / VISION','A camera sees pixels. A useful system finds a pattern that means something.','/showcase-assets/vision.jpg','IRIS / VISION',array['Computer vision','Python','Edge AI'],'{"category":"ai","subtitle":"EXP—02 / AI CONCEPT","status":"Concept","homeProject":true}'::jsonb,true,1) on conflict(slug) do nothing;
insert into public.content_details(content_id,body) select id,'The first experiment

Choose a small set of everyday objects and explore how a model distinguishes them. Test changing light, angles, and backgrounds before connecting the output to a real-world action. This is a concept study.' from public.content where slug='vision' on conflict(content_id) do nothing;
insert into public.content(kind,slug,title,summary,image,image_alt,tags,data,published,sort_order) values ('project','signal','PULSE / NETWORK','Imagine a room that can tell you how it feels: warmer, brighter, quieter, or busier.','/showcase-assets/vision.jpg','PULSE / NETWORK',array['Sensors','Wireless communication','Dashboards'],'{"category":"iot","subtitle":"EXP—03 / IoT CONCEPT","status":"Concept","homeProject":true}'::jsonb,true,2) on conflict(slug) do nothing;
insert into public.content_details(content_id,body) select id,'The first experiment

Connect one environmental sensor to a microcontroller and display its readings. Then explore multiple nodes, missing readings, and a dashboard that makes the patterns clear. This is a concept study.' from public.content where slug='signal' on conflict(content_id) do nothing;
insert into public.content(kind,slug,title,summary,image,image_alt,tags,data,published,sort_order) values ('project','arm','DEXTER / ARM','A simple pick-and-place task becomes a playground for mechanisms, geometry, and control.','/showcase-assets/rover.jpg','DEXTER / ARM',array['Mechanisms','Servo control','Kinematics'],'{"category":"robotics","subtitle":"EXP—04 / ROBOTICS CONCEPT","status":"Concept","homeProject":true}'::jsonb,true,3) on conflict(slug) do nothing;
insert into public.content_details(content_id,body) select id,'The first experiment

Model a small arm and explore one controlled joint at a time. Begin with a simulation, define movement limits, and work toward repeatable motion with a lightweight prototype. This is a concept study.' from public.content where slug='arm' on conflict(content_id) do nothing;
