-- Run after schema.sql. Seeds existing content; does not overwrite admin edits.
insert into public.content(kind,slug,title,summary,image,image_alt,tags,data,published,sort_order) values ('event','genesis','AI Hackathon: Genesis 2026','48 hours to build the next generation of autonomous intelligence.','/about-assets/ai_hackathon.jpg','AI Hackathon: Genesis 2026',array['AI','Software','Hackathon'],'{"id":"genesis","title":"AI Hackathon: Genesis 2026","shortTitle":"AI HACKATHON","subtitle":"GENESIS 2026","startDate":"2026-12-05","endDate":"2026-12-07","date":"Dec 05–07, 2026","location":"Tech Innovation Hub","image":"hackathon","description":"48 hours to build the next generation of autonomous intelligence.","tags":["AI","Software","Hackathon"],"accentColor":"#00e5ff","prizePool":"3,00,000","symbol":"01","homeBeyond":true,"homeExperience":true,"registrationOpen":false}'::jsonb,true,0) on conflict(slug) do nothing;
insert into public.content_details(content_id,body) select id,'The club will share the full schedule and participation requirements here.' from public.content where slug='genesis' on conflict(content_id) do nothing;
insert into public.content(kind,slug,title,summary,image,image_alt,tags,data,published,sort_order) values ('event','robowars','RoboWars: Steel & Sparks','The ultimate combat robotics competition. Build, fight, survive. 30+ teams competing for glory.','/showcase-assets/rover.jpg','RoboWars: Steel & Sparks',array['Hardware','Combat','Robotics'],'{"id":"robowars","title":"RoboWars: Steel & Sparks","shortTitle":"ROBOWARS","subtitle":"STEEL & SPARKS","startDate":"2026-11-15","endDate":"2026-11-15","date":"Nov 15, 2026","location":"Main Arena","image":"robotics","description":"The ultimate combat robotics competition. Build, fight, survive. 30+ teams competing for glory.","tags":["Hardware","Combat","Robotics"],"accentColor":"#ffc107","prizePool":"6,00,000","symbol":"02","homeBeyond":true,"homeExperience":true,"registrationOpen":false}'::jsonb,true,1) on conflict(slug) do nothing;
insert into public.content_details(content_id,body) select id,'The club will share the full schedule and participation requirements here.' from public.content where slug='robowars' on conflict(content_id) do nothing;
insert into public.content(kind,slug,title,summary,image,image_alt,tags,data,published,sort_order) values ('event','iot-summit','IoT Smart Home Summit','Showcasing student-built home automation systems and advanced smart sensors.','/showcase-assets/vision.jpg','IoT Smart Home Summit',array['IoT','Sensors','Showcase'],'{"id":"iot-summit","title":"IoT Smart Home Summit","shortTitle":"IoT SUMMIT","subtitle":"SMART HOME EDITION","startDate":"2026-08-22","endDate":"2026-08-22","date":"Aug 22, 2026","location":"Auditorium B","image":"iot","description":"Showcasing student-built home automation systems and advanced smart sensors.","tags":["IoT","Sensors","Showcase"],"accentColor":"#ff4ca0","prizePool":"1,50,000","symbol":"03","homeBeyond":true,"homeExperience":true,"registrationOpen":false}'::jsonb,true,2) on conflict(slug) do nothing;
insert into public.content_details(content_id,body) select id,'The club will share the full schedule and participation requirements here.' from public.content where slug='iot-summit' on conflict(content_id) do nothing;
insert into public.content(kind,slug,title,summary,image,image_alt,tags,data,published,sort_order) values ('project','rover','ATLAS / ROVER','What if a small rover could explore an unfamiliar space and find its own way back?','/showcase-assets/rover.jpg','ATLAS / ROVER',array['Navigation','Sensors','Embedded control'],'{"category":"robotics","subtitle":"EXP—01 / ROBOTICS CONCEPT","status":"Concept","homeProject":true}'::jsonb,true,0) on conflict(slug) do nothing;
insert into public.content_details(content_id,body) select id,'The first experiment

Start with a wheeled platform and a distance sensor. Read the surroundings, stop before an obstacle, then add a simple navigation loop. This is a concept study, not a completed SAC project.' from public.content where slug='rover' on conflict(content_id) do nothing;
insert into public.content(kind,slug,title,summary,image,image_alt,tags,data,published,sort_order) values ('project','vision','IRIS / VISION','A camera sees pixels. A useful system finds a pattern that means something.','/showcase-assets/vision.jpg','IRIS / VISION',array['Computer vision','Python','Edge AI'],'{"category":"ai","subtitle":"EXP—02 / AI CONCEPT","status":"Concept","homeProject":true}'::jsonb,true,1) on conflict(slug) do nothing;
insert into public.content_details(content_id,body) select id,'The first experiment

Choose a small set of everyday objects and explore how a model distinguishes them. Test changing light, angles, and backgrounds before connecting the output to a real-world action. This is a concept study.' from public.content where slug='vision' on conflict(content_id) do nothing;
insert into public.content(kind,slug,title,summary,image,image_alt,tags,data,published,sort_order) values ('project','signal','PULSE / NETWORK','Imagine a room that can tell you how it feels: warmer, brighter, quieter, or busier.','/showcase-assets/vision.jpg','PULSE / NETWORK',array['Sensors','Wireless communication','Dashboards'],'{"category":"iot","subtitle":"EXP—03 / IoT CONCEPT","status":"Concept","homeProject":true}'::jsonb,true,2) on conflict(slug) do nothing;
insert into public.content_details(content_id,body) select id,'The first experiment

Connect one environmental sensor to a microcontroller and display its readings. Then explore multiple nodes, missing readings, and a dashboard that makes the patterns clear. This is a concept study.' from public.content where slug='signal' on conflict(content_id) do nothing;
insert into public.content(kind,slug,title,summary,image,image_alt,tags,data,published,sort_order) values ('project','arm','DEXTER / ARM','A simple pick-and-place task becomes a playground for mechanisms, geometry, and control.','/showcase-assets/rover.jpg','DEXTER / ARM',array['Mechanisms','Servo control','Kinematics'],'{"category":"robotics","subtitle":"EXP—04 / ROBOTICS CONCEPT","status":"Concept","homeProject":true}'::jsonb,true,3) on conflict(slug) do nothing;
insert into public.content_details(content_id,body) select id,'The first experiment

Model a small arm and explore one controlled joint at a time. Begin with a simulation, define movement limits, and work toward repeatable motion with a lightweight prototype. This is a concept study.' from public.content where slug='arm' on conflict(content_id) do nothing;

-- Persist member-only briefs for concept projects.
-- Fill missing JSON keys only; keep explicit edits, empty fields and custom images.
-- The project trigger moves briefs into protected content_details in this transaction.
begin;

update public.content set
  data='{"overview":"Atlas explores how a small wheeled robot could sense an unfamiliar indoor space and choose its next move. The concept starts with reliable movement and obstacle detection before attempting more ambitious navigation.","challenge":"A useful rover needs to react to obstacles, handle imperfect sensor readings, and stop predictably when a command or connection is lost. The first goal is controlled exploration in a small, supervised test area.","approach":"Build and test the drive base first. Add distance sensing and a stop-on-obstacle loop, then log what the robot sees. Use those observations to compare simple navigation strategies before considering mapping.","features":"Obstacle-aware movement\nManual control with a stop command\nSensor readings and movement logs\nA modular base for later navigation experiments","techStack":"Microcontroller and motor driver\nDistance sensors or compact lidar\nWheel encoders\nEmbedded C/C++ or MicroPython\nPython for log analysis","milestones":"Define the test area and movement limits\nValidate motor control and stopping\nIntegrate sensing and obstacle detection\nCompare navigation runs and document failures","nextSteps":"Choose a drive platform, document the wiring and power requirements, and run a short supervised movement test. Record limitations before adding autonomous behaviour.","imageCaption":"Illustrative concept render","githubUrl":""}'::jsonb || coalesce((select d.data from public.content_details d where d.content_id=content.id),'{}'::jsonb) || coalesce(data,'{}'::jsonb),
  image=case when image in ('/showcase-assets/rover.jpg','/showcase-assets/vision.jpg','showcase-assets/rover.jpg','showcase-assets/vision.jpg') then '/showcase-assets/project-atlas.jpg' else image end,
  image_alt=case when image in ('/showcase-assets/rover.jpg','/showcase-assets/vision.jpg','showcase-assets/rover.jpg','showcase-assets/vision.jpg') then 'Concept render of an assembled white autonomous rover with four wheels and a lidar sensor.' else image_alt end
where kind='project' and slug='rover';

update public.content set
  data='{"overview":"Iris is a computer-vision concept for turning a camera feed into useful observations. A first version could recognise a small set of objects on a workbench and explain how confidently it identifies them.","challenge":"Lighting, backgrounds, camera position, and similar-looking objects can all change a model’s predictions. A meaningful demonstration should show both successful detections and cases where the system is uncertain.","approach":"Start with a fixed camera and a small, documented set of sample objects. Build a repeatable capture pipeline, compare a simple baseline with a trained model, and inspect errors using images excluded from training.","features":"Live camera preview\nObject labels and confidence display\nA small, documented evaluation set\nClear handling of uncertain predictions","techStack":"USB or board camera\nPython and OpenCV\nA lightweight vision model\nImage annotation tools\nLocal inference interface","milestones":"Choose the objects and capture conditions\nCollect and label representative images\nBuild a baseline and inspect mistakes\nEvaluate on held-out examples and document limits","nextSteps":"Agree on one recognition task and collect an initial set of example images. Define what counts as a useful prediction before choosing a model.","imageCaption":"Illustrative concept render","githubUrl":""}'::jsonb || coalesce((select d.data from public.content_details d where d.content_id=content.id),'{}'::jsonb) || coalesce(data,'{}'::jsonb),
  image=case when image in ('/showcase-assets/rover.jpg','/showcase-assets/vision.jpg','showcase-assets/rover.jpg','showcase-assets/vision.jpg') then '/showcase-assets/project-iris.jpg' else image end,
  image_alt=case when image in ('/showcase-assets/rover.jpg','/showcase-assets/vision.jpg','showcase-assets/rover.jpg','showcase-assets/vision.jpg') then 'Concept render of a compact vision camera observing geometric sample objects.' else image_alt end
where kind='project' and slug='vision';

update public.content set
  data='{"overview":"Pulse imagines a small network of environmental sensors that makes changes in a room easier to understand. Individual readings become a shared view of temperature, humidity, or light over time.","challenge":"A dashboard should distinguish fresh readings from stale or missing data. Sensors also need calibration checks, consistent timestamps, and a clear explanation of what each measurement represents.","approach":"Connect one sensor node and display its readings locally. Add a simple message format, then connect multiple nodes to a dashboard. Test disconnections and missing readings before expanding the network.","features":"Multiple named sensor nodes\nLive readings and historical trends\nLast-seen indicators for each device\nConfigurable thresholds for environmental changes","techStack":"Wi-Fi microcontroller\nEnvironmental sensor modules\nMQTT or HTTP messaging\nTime-series storage\nWeb dashboard","milestones":"Read and sanity-check one sensor\nSend timestamped readings to a receiver\nDisplay multiple nodes on a dashboard\nTest reconnects, missing data, and threshold rules","nextSteps":"Pick the measurements that matter for one room, assemble a single node, and agree on a common data format before building the dashboard.","imageCaption":"Illustrative concept render","githubUrl":""}'::jsonb || coalesce((select d.data from public.content_details d where d.content_id=content.id),'{}'::jsonb) || coalesce(data,'{}'::jsonb),
  image=case when image in ('/showcase-assets/rover.jpg','/showcase-assets/vision.jpg','showcase-assets/rover.jpg','showcase-assets/vision.jpg') then '/showcase-assets/project-pulse.jpg' else image end,
  image_alt=case when image in ('/showcase-assets/rover.jpg','/showcase-assets/vision.jpg','showcase-assets/rover.jpg','showcase-assets/vision.jpg') then 'Concept render of three compact wireless environmental sensor nodes.' else image_alt end
where kind='project' and slug='signal';

update public.content set
  data='{"overview":"Dexter is a motion-control concept centred on a small tabletop robotic arm. Its first experiment is a repeatable pick-and-place movement using a lightweight object and a clearly defined workspace.","challenge":"Joint limits, mechanical play, object position, and movement speed affect repeatability. The build should start with one controlled joint and a simple stop mechanism before coordinating an entire arm.","approach":"Model the arm geometry, explore joint motion in simulation, and verify each actuator individually. Add a gripper and slowly combine joints into a repeatable movement sequence within tested limits.","features":"Individual joint control\nDefined movement limits\nA lightweight pick-and-place routine\nRecorded positions for repeatable sequences","techStack":"Servo motors and controller\nLightweight links and gripper\nCAD and motion simulation\nEmbedded control firmware\nBasic kinematics","milestones":"Define reach, joint limits, and a small test object\nSimulate the intended movement\nTest one joint and a stop command\nCombine movements and measure repeatability","nextSteps":"Sketch a simple arm, select a lightweight test object, and validate a single joint. Keep the first movement slow and supervised while documenting the mechanism.","imageCaption":"Illustrative concept render","githubUrl":""}'::jsonb || coalesce((select d.data from public.content_details d where d.content_id=content.id),'{}'::jsonb) || coalesce(data,'{}'::jsonb),
  image=case when image in ('/showcase-assets/rover.jpg','/showcase-assets/vision.jpg','showcase-assets/rover.jpg','showcase-assets/vision.jpg') then '/showcase-assets/project-dexter.jpg' else image end,
  image_alt=case when image in ('/showcase-assets/rover.jpg','/showcase-assets/vision.jpg','showcase-assets/rover.jpg','showcase-assets/vision.jpg') then 'Concept render of an assembled desktop robotic arm reaching toward a green cube.' else image_alt end
where kind='project' and slug='arm';

commit;
