import React from 'react';
import { ArrowUpRight, CircleHelp } from 'lucide-react';
import { RobotAvatar } from './robot-avatar.jsx';
import '../avatars.css';
export function Brand() { return <a className="portal-brand" href="/"><span className="brand-mark">sac<span>✳</span></span><span>Sensing &<br/>Automation Club</span></a>; }
export function Notice({children,error=false}) { return children ? <div className={`notice ${error?'notice-error':''}`} role={error?'alert':'status'}>{children}</div> : null; }
export function Field({label,area=false,children,...props}) { return <label className="field"><span>{label}</span>{children || (area?<textarea rows={4} {...props}/>:<input {...props}/>)}</label>; }
export function AvatarPicker({value,onChange}) { return <fieldset className="avatar-picker"><legend>Your robot avatar</legend>{[['boy','Boy'],['girl','Girl']].map(([id,label])=><label key={id} data-avatar={id} className={value===id?'selected':''}><input type="radio" name="avatar" value={id} checked={value===id} onChange={()=>onChange(id)}/><RobotAvatar variant={id} decorative/>{label}</label>)}</fieldset>; }
export function AuthLayout({admin=false,children}) { return <div className="auth-layout"><aside className="auth-story"><Brand/><div><span className="eyebrow">{admin?'THE SPACE BEHIND THE SCENES':'YOUR NEXT CHAPTER STARTS HERE'}</span><h1>{admin?<>Good things.<br/>Well organized.</>:<>Curious minds.<br/>One community.</>}</h1><p>{admin?'A little space to keep the club moving. Shape the stories, welcome new members, and make room for what’s next.':'Join the people turning ideas into experiments. Your projects, events, and next collaborators are waiting.'}</p><div className="story-art" aria-hidden="true"><span>✳</span><div/><i/></div></div><a className="back-link" href="/">Back to the website <ArrowUpRight size={16}/></a></aside><main className="auth-main">{children}<p className="auth-foot"><CircleHelp size={14}/> Sensing & Automation Club · Member services</p></main></div>; }
